### ISSUE TITLE
axios非対応環境下でエラーが発生する

### ISSUE THREAD

**Issue by saladbowl77** [Newt-Inc/newt-client-js#52]
## 内容
cloudflare pagesでbuildしようとするとCloudflare Pages 並びに Cloudflare Workers でエラーが発生する。

## 原因
Cloudflare Workersではaxiosが非対応(XMLHttpRequestに非対応のため芋蔓式に非対応になっている)のためエラーになる。
Pagesが非対応であるという明確な文書は見つけられなかったため憶測にはなるが、同様に非対応のためエラーが発生するとみられる。

Cloudflare Workersでのエラー内容
```log
  (error) TypeError: adapter is not a function
    at dispatchRequest (worker.js:1411:14)
    at async Object.w [as getContents] (worker.js:3937:32)
    at async load (worker.js:3993:15)
    at async load_server_data (worker.js:5319:18)
    at async worker.js:6241:18
```
(Pagesではlogを見ることができない)

## 参考
[[Bug]: Using axios inside loader throws exception · Issue #1318 · remix-run/remix](https://github.com/remix-run/remix/issues/1318)
[TypeError: (e.adapter || s.adapter) is not a function - Developers / Workers - Cloudflare Community](https://community.cloudflare.com/t/typeerror-e-adapter-s-adapter-is-not-a-function/166469/3)
[Feature request: fetch based adapter · Issue #1219 · axios/axios](https://github.com/axios/axios/issues/1219)

[元ツイート](https://twitter.com/saladbowl_dev/status/1583756551869063169)

**Comment by saladbowl77** [comment]
@y-meguro 
深夜になりすみません。

検証ありがとうございます。

1. 使用しているフレームワークについて
使用しているフレームワークはSvelteKitになっています。
また、エラーが発生原因となっているのは、+page.server.jsというサーバー側で処理ができるといった機能によるものになります。
以下のページにでもサイトを作成しました。(ドキュメント → https://kit.svelte.jp/docs/routing#page-page-js )
https://newt-svelte-kit-test.pages.dev
(コードはこちらになります https://github.com/saladbowl77/newt-svelte-kit-test )
nextjsに関しては触った経験がなく同じような機能がどれなのか、コード同士の比較ができません。申し訳ありません。

2. ビルドログについて
紛らわしくてすみません。
ビルドログではなくサーバーのログになります。
Workersではサーバーログを見ることができます。(wrangler tail コマンド)

**Comment by y-meguro** [comment]
@saladbowl77 こちら状況再現できました！丁寧にありがとうございます！🙇

**Comment by y-meguro** [comment]
### 対応案

1. axiosを外して、fetch APIを使うようにする

Nuxt3で使われている [unjs/ohmyfetch](https://github.com/unjs/ohmyfetch) などを使えば、Node.js環境でも動かせる。

2. adapterを設定できるようにする

axiosのadapterとして、例えば [vespaiach/axios-fetch-adapter](https://github.com/vespaiach/axios-fetch-adapter) などを使えば、axiosでfetch APIが利用できる。

### 今回の対応

2のadapterの設定で対応する。
既存のaxiosの機能を保ったまま、fetch APIを利用できるようにする。
今後、不便さが増したりするようであれば、axios自体のリプレイスも検討する。

**Comment by y-meguro** [comment]
@saladbowl77 
こちらaxiosのadapterオプションを設定できるようにして、対応しました。`v3.2.0` をご利用いただければと思います。

fetch APIを利用する場合、[vespaiach/axios-fetch-adapter](https://github.com/vespaiach/axios-fetch-adapter) などを利用することとなります。

使い方の例は、以下の通りです。

```
// src/routes/server/+page.server.js

import { createClient } from 'newt-client-js';
import { env } from '$env/dynamic/private';
import fetchAdapter from "@vespaiach/axios-fetch-adapter";

export function load() {
  async function getdata() {
    const client = createClient({
      spaceUid: 'test-blog',
      token: env.TOKEN,
      apiType: 'cdn',
      adapter: fetchAdapter,
    });

    //（以下、省略）
}
```

また、この時 `Cannot use import statement outside a module` のエラーが出るかと思いますので、vite.config.js の `ssr.noExternal` の記載も必要となります。

```
// vite.config.js

import { sveltekit } from "@sveltejs/kit/vite";

const config = {
  plugins: [sveltekit()],
  ssr: {
    noExternal: "@vespaiach/axios-fetch-adapter",
  },
};

export default config;
```

以下のメッセージは表示されてしまいますが、こちらのadapterオプションをご利用いただくことで、fetch APIの利用が可能になります。（また他のadapterをご利用いただくことも可能です）

```
@vespaiach/axios-fetch-adapter doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.
```

こちらの対応でこのissueはcloseとさせていただきますが、もしまた不明点や不具合等ありましたら、遠慮なく聞いていただければと思います。
issueの作成ありがとうございました。引き続きよろしくお願いいたします🙌

**Comment by Kanahiro** [comment]
Sveltekit v2で上記を参考に実装してみましたが、axiosの依存解決やCJS/ESM周りのエラーの解決がなかなか厳しかったので、`fetch`を利用するクライアントを簡単にスクラッチで書くことで解決しました。not well testedですが、スニペットを共有いたします。

```typescript
import type {
	Content,
	Image,
	GetContentsQuery,
	Contents,
	GetContentsParams,
	GetContentParams,
	GetFirstContentParams,
	GetAppParams,
	AppMeta
} from 'newt-client-js';

type Client = {
	getContents: <T>({ appUid, modelUid, query }: GetContentsParams) => Promise<Contents<T>>;
	getContent: <T>({ appUid, modelUid, contentId, query }: GetContentParams) => Promise<T>;
	getFirstContent: <T>({ appUid, modelUid, query }: GetFirstContentParams) => Promise<T | null>;
	getApp: ({ appUid }: GetAppParams) => Promise<AppMeta>;
};

type CreateClientOptions = {
	spaceUid: string;
	token: string;
};

const createClient = (options: CreateClientOptions): Client => {
	const { spaceUid, token } = options;
	const baseUrl = `https://${spaceUid}.cdn.newt.so/v1`;
	const authorization = `Bearer ${token}`;

	const getContents = async <T>({ appUid, modelUid, query }: GetContentsParams) => {
		const url = new URL(`${baseUrl}/${appUid}/${modelUid}`);
		if (query) {
			url.search = new URLSearchParams(query as Record<string, string>).toString();
		}
		const response = await fetch(url.toString(), {
			headers: {
				authorization
			}
		});
		const data = await response.json();
		return data as Contents<T>;
	};

	const getContent = async <T>({ appUid, modelUid, contentId, query }: GetContentParams) => {
		const url = new URL(`${baseUrl}/${appUid}/${modelUid}/${contentId}`);
		if (query) {
			url.search = new URLSearchParams(query as Record<string, string>).toString();
		}
		const response = await fetch(url.toString(), {
			headers: {
				authorization
			}
		});
		const data = await response.json();
		return data as T;
	};

	const getFirstContent = async <T>({ appUid, modelUid, query }: GetFirstContentParams) => {
		const res = await getContents<T>({ appUid, modelUid, query });
		return res.items[0];
	};

	const getApp = async ({ appUid }: GetAppParams) => {
		const url = `${baseUrl}/space/apps/${appUid}`;
		const response = await fetch(url.toString(), {
			headers: {
				authorization
			}
		});
		const data = await response.json();
		return data as AppMeta;
	};

	return {
		getContents,
		getContent,
		getFirstContent,
		getApp
	};
};
```
